/**
 * Version Streams Type Definitions
 *
 * Core types for the version streams architecture where each panel
 * (voices, music, sound effects) maintains an independent, immutable
 * version history with active pointers.
 */

import {
  VoiceTrack,
  MusicPrompts,
  MusicProvider,
  SoundFxPrompt,
  ProjectBrief
} from "./index";

// Re-export types needed by tests
export type { VoiceTrack, SoundFxPrompt };

// ============ Version Identifiers ============

/**
 * Version ID format: "v1", "v2", "v3", etc.
 * Integer-based for simplicity and sortability
 */
export type VersionId = string;

/**
 * Stream types corresponding to the three main panels
 */
export type StreamType = "voices" | "music" | "sfx";

/**
 * Version lifecycle status
 * - draft: Editable, work-in-progress
 * - frozen: Immutable, no longer editable (superseded by newer draft)
 */
export type VersionStatus = "draft" | "frozen";

/**
 * Provenance tracking for version creation
 * - llm: Generated by AI creative generation
 * - user: Manually created/edited by user
 * - fork: Duplicated from another version
 */
export type CreatedBy = "llm" | "user" | "fork";

// ============ Voice Version Stream ============

/**
 * Immutable version entry in the voice stream
 * Contains script segments with voice selections and generation results
 */
export interface VoiceVersion {
  /** Voice track definitions (script + voice selections, each with embedded generatedUrl) */
  voiceTracks: VoiceTrack[];

  /** @deprecated Use voiceTracks[i].generatedUrl instead - kept for migration only */
  generatedUrls?: string[];

  /** Unix timestamp when version was created */
  createdAt: number;

  /** Who/what created this version */
  createdBy: CreatedBy;

  /** Current lifecycle status */
  status: VersionStatus;

  /** Optional: Original LLM prompt that generated this version */
  promptContext?: string;

  /** Optional: Parent version ID if this was iterated from */
  parentVersionId?: VersionId;

  /** Optional: User request that created this iteration */
  requestText?: string;
}

/**
 * Helper type for tracking per-track generation status in UI
 * Used by VoiceDraftEditor to manage individual track generation
 */
export interface VoiceTrackGenerationStatus {
  /** Track index in voiceTracks array */
  index: number;

  /** Whether this track has generated audio */
  hasAudio: boolean;

  /** Whether this track is currently generating */
  isGenerating: boolean;

  /** Whether this track is currently playing */
  isPlaying: boolean;
}

// ============ Music Version Stream ============

/**
 * Immutable version entry in the music stream
 * Contains music generation prompts and results
 */
export interface MusicVersion {
  /** User-facing music generation prompt */
  musicPrompt: string;

  /** Provider-specific prompts (Loudly, Mubert, ElevenLabs) */
  musicPrompts: MusicPrompts;

  /** Generated music blob URL */
  generatedUrl: string;

  /** Track duration in seconds */
  duration: number;

  /** Music provider used for generation */
  provider: MusicProvider;

  /** Unix timestamp when version was created */
  createdAt: number;

  /** Who/what created this version */
  createdBy: CreatedBy;

  /** Current lifecycle status */
  status: VersionStatus;

  /** Optional: Parent version ID if this was iterated from */
  parentVersionId?: VersionId;

  /** Optional: User request that created this iteration */
  requestText?: string;
}

// ============ Sound Effects Version Stream ============

/**
 * Immutable version entry in the sound effects stream
 * Contains multiple SFX prompts with placement and generation results
 */
export interface SfxVersion {
  /** Array of sound effect prompts with placement instructions */
  soundFxPrompts: SoundFxPrompt[];

  /** Generated SFX blob URLs (parallel array to soundFxPrompts) */
  generatedUrls: string[];

  /** Unix timestamp when version was created */
  createdAt: number;

  /** Who/what created this version */
  createdBy: CreatedBy;

  /** Current lifecycle status */
  status: VersionStatus;

  /** Optional: Parent version ID if this was iterated from */
  parentVersionId?: VersionId;

  /** Optional: User request that created this iteration */
  requestText?: string;
}

// ============ Ad Metadata ============

/**
 * Advertisement-level metadata
 * Stored separately from version streams
 */
export interface AdMetadata {
  /** Human-readable ad name */
  name: string;

  /** Creative brief and settings */
  brief: ProjectBrief;

  /** Unix timestamp when ad was created */
  createdAt: number;

  /** Unix timestamp of last modification */
  lastModified: number;

  /** Owner identifier (currently "universal-session") */
  owner: string;
}

// ============ API Response Types ============

/**
 * Response type for listing all versions in a stream
 * Used by GET /api/ads/{adId}/voices|music|sfx
 */
export interface VersionStreamResponse {
  /** Ordered list of version IDs (v1, v2, v3, ...) */
  versions: VersionId[];

  /** Currently active version ID (or null if none) */
  active: VersionId | null;

  /** Full version data indexed by version ID */
  versionsData: Record<VersionId, VoiceVersion | MusicVersion | SfxVersion>;
}

/**
 * Response type for creating a new version
 * Used by POST /api/ads/{adId}/voices|music|sfx
 */
export interface CreateVersionResponse {
  /** Generated version ID (e.g., "v4") */
  versionId: VersionId;

  /** Initial status (always "draft") */
  status: VersionStatus;
}

/**
 * Response type for activating a version
 * Used by POST /api/ads/{adId}/voices|music|sfx/{versionId}/activate
 */
export interface ActivateVersionResponse {
  /** Newly activated version ID */
  active: VersionId;

  /** Rebuilt mixer state (optional, for immediate UI update) */
  mixer?: MixerState;
}

/**
 * Mixer state derived from active versions
 * Stored at ad:{adId}:mixer
 */
export interface MixerState {
  /** All tracks from active versions combined */
  tracks: MixerTrack[];

  /** Volume overrides per track */
  volumes: Record<string, number>;

  /** Timeline-positioned tracks with calculated start times */
  calculatedTracks: CalculatedTrack[];

  /** Total duration of the ad in seconds */
  totalDuration: number;

  /** Unix timestamp of last calculation */
  lastCalculated: number;

  /** Snapshot of active versions used for this mixer state */
  activeVersions: {
    voices: VersionId | null;
    music: VersionId | null;
    sfx: VersionId | null;
  };

  /** Permanent URL of final mixed audio (uploaded to blob storage) */
  mixedAudioUrl?: string;
}

/**
 * Mixer track (imported from existing types)
 * TODO: Import from mixer store types when refactoring
 */
export interface MixerTrack {
  id: string;
  url: string;
  label: string;
  type: "voice" | "music" | "soundfx";
  startTime?: number;
  duration?: number;
  volume?: number;
  playAfter?: string | "start";
  overlap?: number;
  isConcurrent?: boolean;
  metadata?: Record<string, unknown>;
}

/**
 * Calculated track with timeline position
 * TODO: Import from mixer store types when refactoring
 */
export interface CalculatedTrack {
  id: string;
  startTime: number;
  duration: number;
  type: "voice" | "music" | "soundfx";
}
